DROP TABLE ODDZIALY CASCADE CONSTRAINTS;
DROP TABLE Spedytorzy CASCADE CONSTRAINTS;
DROP TABLE Samochody CASCADE CONSTRAINTS;
DROP TABLE Kierowcy CASCADE CONSTRAINTS;
DROP TABLE Klienci CASCADE CONSTRAINTS;
DROP TABLE Zlecenie CASCADE CONSTRAINTS;
DROP TABLE Oplaty CASCADE CONSTRAINTS;
DROP TABLE trasa CASCADE CONSTRAINTS;
DROP TABLE naprawy CASCADE CONSTRAINTS;
DROP TABLE ADRESY CASCADE CONSTRAINTS;
DROP TABLE TYP_KLIENT CASCADE CONSTRAINTS;

CREATE TABLE ADRESY(
ID NUMBER(3) CONSTRAINT ADRESY_PK PRIMARY KEY,
NR_DOMU NUMBER(6),
Miejscowosc VARCHAR2(30),
Kod_Pocztowy VARCHAR2(30)
);

CREATE TABLE ODDZIALY(
ID NUMBER(3) CONSTRAINT ODDZIALY_PK PRIMARY KEY,
Telefon NUMBER(11),
FAX NUMBER(11),
Budzet NUMBER(20),
ID_ADRESY NUMBER(3) NOT NULL,
CONSTRAINT ODDZIALY_ADRESY_FK FOREIGN KEY(ID_ADRESY) REFERENCES ADRESY(ID)
);

CREATE TABLE SPEDYTORZY(
ID NUMBER(3) CONSTRAINT SPEDYTORZY_PK PRIMARY KEY,
Imie VARCHAR2(30),
Nazwisko VARCHAR2(30),
Zarobki NUMBER(9,2),
ID_ODDZIALY NUMBER(3) NOT NULL,
CONSTRAINT SPEDYTORZY_ODDZIALY_FK FOREIGN KEY(ID_ODDZIALY) REFERENCES ODDZIALY(ID)
);

CREATE TABLE SAMOCHODY(
ID NUMBER(3) CONSTRAINT SAMOCHODY_PK PRIMARY KEY,
Marka VARCHAR2(30),
Przebieg NUMBER(9),
Rok_produkcji NUMBER(4),
Ladownosc_naczepy NUMBER(6),
Typ_Naczepy VARCHAR2(30)
);

CREATE TABLE KIEROWCY(
ID NUMBER(3) CONSTRAINT KIEROWCY_PK PRIMARY KEY,
Imie VARCHAR2(30),
Nazwisko VARCHAR2(30),
Zarobki NUMBER(9,2),
Wiek NUMBER(2),
ID_Samochody NUMBER(3) NOT NULL,
CONSTRAINT KIEROWCY_SAMOCHODY_FK FOREIGN KEY(ID_SAMOCHODY) REFERENCES SAMOCHODY(ID),
ID_SPEDYTORZY NUMBER(3) NOT NULL,
CONSTRAINT KIEROWNCY_SPEDYTORZY_FK FOREIGN KEY(ID_SPEDYTORZY) REFERENCES SPEDYTORZY(ID)
);

CREATE TABLE KLIENCI(
ID NUMBER(3) CONSTRAINT KLIENCI_PK PRIMARY KEY,
IMIE VARCHAR2(30),
Nazwisko VARCHAR2(30),
TELEFON NUMBER(9),
ID_Spedytorzy NUMBER(3) NOT NULL,
CONSTRAINT KLIENCI_SPEDYTORZY_FK FOREIGN KEY(ID_SPEDYTORZY) REFERENCES SPEDYTORZY(ID)
);

CREATE TABLE ZLECENIE(
ID NUMBER(3) CONSTRAINT ZLECENIE_PK PRIMARY KEY,
Nazwa_Ladunku VARCHAR2(30),
Cena_zlecenia NUMBER(9),
Czas_dostawy NUMBER(3),
Stan VARCHAR2(30),
ID_Klienci NUMBER(3) NOT NULL,
CONSTRAINT ZLECENIE_KLIENCI_FK FOREIGN KEY(ID_KLIENCI) REFERENCES KLIENCI(ID)
);

CREATE TABLE OPLATY(
ID NUMBER(3) CONSTRAINT OPLATY_PK PRIMARY KEY,
Termin DATE,
Status VARCHAR2(30),
Kwota NUMBER(9),
ID_ZLECENIE NUMBER(3) NOT NULL,
CONSTRAINT OPLATY_ZLECENIE_FK FOREIGN KEY(ID_ZLECENIE) REFERENCES ZLECENIE(ID)
);

CREATE TABLE TRASA(
ID NUMBER(3) CONSTRAINT TRASA_PK PRIMARY KEY,
Ilosc_km NUMBER(9),
Poczatek_trasy VARCHAR2(30),
Koniec_trasy VARCHAR2(30),
ID_ZLECENIE NUMBER(3) NOT NULL,
CONSTRAINT TRASA_ZLECENIE_FK FOREIGN KEY(ID_ZLECENIE) REFERENCES ZLECENIE(ID)
);

CREATE TABLE NAPRAWY(
ID NUMBER(3) CONSTRAINT NAPRAWY_PK PRIMARY KEY,
DATA DATE,
USTERKA VARCHAR2(30),
KOSZT NUMBER(9),
ID_Samochody NUMBER(3) NOT NULL,
CONSTRAINT NAPRAWY_SAMOCHODY_FK FOREIGN KEY(ID_SAMOCHODY) REFERENCES SAMOCHODY(ID)
);

CREATE TABLE TYP_KLIENT(
ID NUMBER(5) CONSTRAINT TYP_KLIENT_PK PRIMARY KEY,
TYP VARCHAR2(30),
ID_KLIENCI NUMBER(3) NOT NULL ,
CONSTRAINT TYP_KLIENT_KLIENCI_FK FOREIGN KEY(ID_KLIENCI) REFERENCES KLIENCI(ID),
ID_ADRESY NUMBER(3) NOT NULL,
CONSTRAINT TYP_KLIENT_ADRESY_FK FOREIGN KEY(ID_ADRESY)  REFERENCES ADRESY(ID)
);


